### ISSUE TITLE
Unable to resolve module StyleSheet from /.../node_modules/react-native-autocomplete/RCTAutoComplete.ios.js

### ISSUE THREAD

**Issue by alfondotnet** [nulrich/RCTAutoComplete#11]
Getting this Error:

> Unable to resolve module StyleSheet from /.../node_modules/react-native-autocomplete/RCTAutoComplete.ios.js

Not being used anyway, commenting the line does it

**Comment by nulrich** [comment]
Fixed in https://github.com/nulrich/RCTAutoComplete/commit/c541521b0064f9437402b5f8e93e1ad2d12ff9c7

**Comment by nulrich** [comment]
Thanks!
