### ISSUE TITLE
Keyboard doesn't hide unless item selected

### ISSUE THREAD

**Issue by hmm29** [nulrich/RCTAutoComplete#12]
Keyboard doesn't hide unless an option is selected

Even in the example provided, it's not possible to hide the keyboard if the autocomplete input value is an empty string.

Can you make it so that the keyboard hides when the user presses the keyboard return button, even if he/she hasn't selected an option?

**Comment by hmm29** [comment]
how can i force the autocomplete component to blur?

**Comment by ChrisPTsang** [comment]
I have the same problem where I'd like to use onSubmitEditing to invoke a callback to do a search.

**Comment by nulrich** [comment]
Fixed in 0.1.0. And @hmm29, I will have a look to your Blur question.

**Comment by ChrisPTsang** [comment]
Thanks!

**Comment by enapupe** [comment]
I'm lost with this one..  I cannot understand how I am supposed to make the keyboard disappear.. It was supposed to happen when a tap happens anywhere but the input? The only way I'm being able to hide it is by choosing an option from the autocomplete
