### ISSUE TITLE
No description re: how to style the autocomplete suggestions box?

### ISSUE THREAD

**Issue by hmm29** [nulrich/RCTAutoComplete#15]
By default, the autocomplete dropdown overlaps with the text bar, and I'd like to create space between the text bar and the dropdown

How can we style the component to push the dropdown down so that it shares a border with the bottom of the text bar, instead of overlapping the text bar?

**Comment by nulrich** [comment]
Fixed in https://github.com/nulrich/RCTAutoComplete/commit/0fc0d862fdb2e75d79c2f0019febcf2e431941c4

You can now set the offset between TextField and Dropdown.
