### ISSUE TITLE
Passing custom objects instead of strings 

### ISSUE THREAD

**Issue by alfondotnet** [nulrich/RCTAutoComplete#16]
Would there be a way of passing custom objects with a `autocompleteString` method in order to provide for better functionality (such as returning not a string but the id of the object or such).

My goal is to be able to pass this check: https://github.com/EddyBorja/MLPAutoCompleteTextField/blob/master/MLPAutoCompleteTextField/MLPAutoCompleteTextField.m#L933

I am _nil_ in Objective-C, but I will try to take a look :-).

Cheers!

**Comment by alfondotnet** [comment]
Taking a wild guess, could creating a [dynamic class](http://www.infragistics.com/community/blogs/stevez/archive/2014/06/10/ios-objective-c-advanced-creating-a-class-at-runtime.aspx) that implements the protocol `MLPAutoCompletionObject` and passing a `NSArray` of instances of that class to `self.handler` in [setSuggestions](https://github.com/nulrich/RCTAutoComplete/blob/master/AutoCompleteView.m#L22) starts doing it?, I did something similar and it worked for the suggestions, but then how to pass the object back on Select?

It seems easier to work directly with the NSDictionary that is passed on by RN, any hint from a real iOS developer? :-)

**Comment by danleveille** [comment]
@alfonsoperez Would love to see this implemented!

**Comment by chibeepatag** [comment]
Custom cell accomplishes this.
