### ISSUE TITLE
Displaying the autocomplete box on focus

### ISSUE THREAD

**Issue by GabrielGhe** [nulrich/RCTAutoComplete#19]
Is there a way to display the dropdown and it's unfiltered contents when the user focuses the text?

![screen shot 2015-10-18 at 6 01 34 pm](https://cloud.githubusercontent.com/assets/5266128/10566919/4e85027e-75c2-11e5-9eae-a769bc9cbddb.png)

**Comment by nulrich** [comment]
I don't think MLPAutoComplete can do that.
