### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by aintnorest** [nulrich/RCTAutoComplete#2]
after i link binaries with libraries adding libRCTAutoComplete.a the project fails to build if I remove it it will build again but the autocomplete input isn't focusable.

**Comment by shantanuraj** [comment]
Here's a screenshot of the error messages on build

![screenshot 2015-07-15 17 39 33](https://cloud.githubusercontent.com/assets/1716853/8698122/85e8c5c4-2b18-11e5-88a1-77ae2cfb9543.png)

**Comment by nulrich** [comment]
If I create a new project through react-native, add the Library and add libRCTAutoComplete.a to the build phase, it works.

@aintorest Do you have the same logs as @shantanuraj ?
@shantanuraj Are you trying to build the project alone ? Or is it your own project with the Library included? 

Sorry for the dumb questions, it's my first Xcode project.

**Comment by shantanuraj** [comment]
I’m including it in my own project,

From my package.json
    "dependencies": {
        "immutable": "^3.7.4",
        "react": "^0.13.3",
        "react-native": "^0.5.0",
        "react-native-autocomplete": "0.0.2",
        "react-native-cookies": "0.0.1",
        "react-native-icons": "0.0.9",
        "react-native-modal": "^0.3.8",
        "react-native-overlay": "^0.2.8",
        "react-timer-mixin": "^0.13.1",
        "reflux": "^0.2.8",
        "tcomb": "^1.0.3",
        "tcomb-form-native": "^0.2.0",
        "tcomb-validation": "^1.0.4"
     }

**Comment by nulrich** [comment]
@shantanuraj, I can reproduce. It's your version of React Native. I didn't put the version dependency in the package.json yet. 

Can you try to upgrade react native to the latest version ?

**Comment by shantanuraj** [comment]
Okay will try, what version are you using? I was having some issues with the latest versions on El Capitan & Xcode 6.4 (which I need so that the app is accepted for submission by Apple)

**Comment by nulrich** [comment]
7.1 but I will check the minimum required and add it in package.json.

**Comment by shantanuraj** [comment]
That'd be awesome. Thanks.

#Github via email is weird.

So the build is passing now that I updated my react-native version to 7.1.
Any suggestions on how I can style the Text Input area?
