### ISSUE TITLE
Not able to style result text or border

### ISSUE THREAD

**Issue by sslash** [nulrich/RCTAutoComplete#29]
![screenshot_16_12_2015__21_02](https://cloud.githubusercontent.com/assets/1174520/11852448/493b8528-a438-11e5-8a51-c70eed307f25.png)

Tried everything. Both the text and the border is always blue.
Using latest version 0.1.2

**Comment by mwcrowley** [comment]
Seconded. Having zero luck styling the text inputs as well as the autocomplete dropdown itself. Using the latest version 0.1.2

**Comment by nulrich** [comment]
I have to 'patch' the MLPAutoCompleteTextField. When styles in the "style" attributes are applied (and they are only applied to the search field) they reset the settings of the dropdown. I'm going to comment the 2 lines that triggered the reset in MLPAutoCompleteTextField.
