### ISSUE TITLE
Dropdown hides behind other content

### ISSUE THREAD

**Issue by shantanuraj** [nulrich/RCTAutoComplete#3]
The dropdown will only overlay above its siblings in the parent view, but does not overlay over the siblings of its parent view.

**Comment by axelg12** [comment]
+1

**Comment by axelg12** [comment]
Be able to style the Autocomplete and dropdown would be awesome !

**Comment by alfonsoperez** [comment]
What about this?
Having something like:

    <View style={styles.wrapper}>
      <Text style={styles.message}>Location</Text>
      <SpotsAutoComplete />
      <View style={styles.wrapper}>
        <Text style={[styles.message]}>Max number of friends</Text>
      </View>
    </View>

Produces this:

![image](https://cloud.githubusercontent.com/assets/3578008/9288150/64d6b336-4338-11e5-8607-91bceed11950.png)

Would there be a way to position the dropdown as absolute so it overlays below elements and not take all the space?

**Comment by alfondotnet** [comment]
What about this?, having:

```
<View style={[styles.wrapper, styles.padding]}>
    <Text style={styles.message}>Location</Text>
      <SpotsAutoComplete />
      <View style={[styles.wrapper]}>
        <Text style={[styles.message]}>Max number of friends</Text>
    </View>
</View>
...
var styles = StyleSheet.create({
    wrapper: {      
    flex: 1,
    },
    padding: {
        paddingTop: 64,
    },
    margin: {
        marginTop: 0,
    },
    message: {
         fontSize: 16,
         fontWeight: '500',
    }
})
```

Produces:

![image](https://cloud.githubusercontent.com/assets/3578008/9288166/2e89297a-4339-11e5-9b8f-c32f2f3c89e8.png)

Have you found a way to position the dropdown as absolute over below elements so it does not take all the space?

**Comment by nulrich** [comment]
Thanks for your messages. I'm in vacation without my Mac. I will take care of this issue when I'm back.

**Comment by nulrich** [comment]
@shantanuraj @axelg12 Sorry but this issue is coming from this https://github.com/facebook/react-native/issues/131

I tried to do like @vjeux is explaining (reverse the rendering) and I can the the dropdown over the sibling view.
