### ISSUE TITLE
Styling TextInput (e.g. padding)

### ISSUE THREAD

**Issue by wsun** [nulrich/RCTAutoComplete#40]
I'd like to be able to make some modifications to how the text shows up in the text input, for example, give it some padding so it's not flush against the side of the input box.

![image](https://cloud.githubusercontent.com/assets/546479/15760697/3acd195a-28c9-11e6-93ad-4bc8279400dc.png)

However, providing `padding` in the styles passed to the component doesn't seem to do anything. Any thoughts on how I can make this happen?

**Comment by nulrich** [comment]
The text rendering is controlled by MLPAutoCompleteTextField / RCTTextField. I mapped to React Native most of the attributes from MLPAutoCompleteTextField / UITextField but maybe I missed some. 

I you can find the attributes that would serve your needs in Objective C, I will expose them to React Native.

**Comment by wsun** [comment]
sounds good!

**Comment by ajoshdee** [comment]
how do i set padding?
