### ISSUE TITLE
xcode 8

### ISSUE THREAD

**Issue by drewwells** [nulrich/RCTAutoComplete#46]
I'm seeing errors in xcode 8

```
RCTAutoComplete.m:98:34: warning:
      'sendInputEventWithName:body:' is deprecated: Use RCTDirectEventBlock or RCTBubblingEventBlock instead [-Wdeprecated-declarations]
    [self.bridge.eventDispatcher sendInputEventWithName:@"topChange" body:event];
                                 ^
In file included from .../ui/node_modules/react-native-autocomplete/RCTAutoComplete.m:2:
In file included from .../ui/node_modules/react-native-autocomplete/RCTAutoComplete.h:2:
In file included from ../../node_modules/react-native/React/Views/RCTViewManager.h:15:
../../node_modules/react-native/React/Base/RCTEventDispatcher.h:76:1: note: 'sendInputEventWithName:body:' has been explicitly marked
      deprecated here
- (void)sendInputEventWithName:(NSString *)name body:(NSDictionary *)body
^
2 warnings and 4 errors generated.

** BUILD FAILED **
```

**Comment by drewwells** [comment]
Looks related to the same this: https://github.com/react-native-community/react-native-svg/pull/124/files

**Comment by nulrich** [comment]
Thanks! I think it can also comes from https://github.com/facebook/react-native/commit/d9737571c43d39af41d539de2dd12c2ceb5cda0e
I will replace the EventDispatcher.

**Comment by nulrich** [comment]
I started to clean up the code for Xcode 8 in branch #46. I will fix the Objective-C code and also move JS code to ES6.

**Comment by drewwells** [comment]
🎆 💥  !

**Comment by nulrich** [comment]
I fixed Objective-C part. You were correct, the problem was coming from RCTFont. But your error log was not complet ;-) so I first thought the issue was coming from the EventDispatcher (which I will soon need to fix anyway).

I should be done with JS code by the end of the week, but you can already start to use what is on the branch #46 (checkout code and npm install path-to-RCTAutoComplete).

**Comment by drewwells** [comment]
Sweet I'll give it a spin

**Comment by drewwells** [comment]
It works!
