### ISSUE TITLE
Styling the autocomplete box

### ISSUE THREAD

**Issue by axelg12** [nulrich/RCTAutoComplete#5]
I've been trying to style the autocomplete box by sending style down as a props with no luck.  I am able to change the style by changing `RCTAutoComplete.ios.js` but that is a bit of a hack.   I also tried changing the code so I could pass down the style but with no luck. 

Can you add this feature or is it impossible ?

**Comment by nulrich** [comment]
Good idea! I will expose the Style attribute. And I will also expose more feature from Autocomplete IOS component.

**Comment by nulrich** [comment]
I have added in 0.0.4 lots of property from UITextField and the style attribute is not hardcoded anymore in RCTAutoComplete.ios.js

**Comment by axelg12** [comment]
+1 Awesome ! Shouldn't we close this issue then ?

**Comment by axelg12** [comment]
`_onFocus` and `_onBlur` functions don't trigger when focusing on the input box. Is there any way to get the onFocus event ?

**Comment by nulrich** [comment]
Fixed. I close the issue
