### ISSUE TITLE
Component rendered but does not response.

### ISSUE THREAD

**Issue by petervavro** [nulrich/RCTAutoComplete#55]
Component rendered but does not response at all. There is warning in the console : "Warning: Native component for "REACT AutoComplete" does not exist". Debugging on Android 5.1.1 . What is wrong ? Thanks

**Comment by nulrich** [comment]
For the moment, this component is only a wrapper for an existing IOS Component. I'm sorry it won't work on Android.

**Comment by asquet** [comment]
I think it would be helpful to mention it in readme.md

**Comment by nulrich** [comment]
👍 Done
