### ISSUE TITLE
Styling the dropdown

### ISSUE THREAD

**Issue by axelg12** [nulrich/RCTAutoComplete#7]
Wow thanks for the awesome and fast reaction to my feedback !  I would hope I could contrib a little to this project but Obj-C isn't my strong suit.  Anyway

Is there any possibility to style the autocomplete dropdown? I want the dropdown to take at least a little bit more space on my Iphone 6 if not all of it.

Thanks again !
<img width="372" alt="screen shot 2015-07-29 at 23 02 01" src="https://cloud.githubusercontent.com/assets/2584475/8972096/3c95e21a-3646-11e5-9b6c-471a351755f7.png">

**Comment by nulrich** [comment]
You're welcome :+1: 

Now that I have exposed features from UITextInput, I'm going to expose MLPAutoCompleteTextField properties. I think you want maximumNumberOfAutoCompleteRows  (https://github.com/EddyBorja/MLPAutoCompleteTextField/blob/master/MLPAutoCompleteTextField/MLPAutoCompleteTextField.h).

**Comment by nulrich** [comment]
done in 0.0.8
